/*
DELETE TABLE REGISTERS
*/

DELETE FROM dbo.CALIFICATIONS;
DELETE FROM dbo.DELIVERABLES;
DELETE FROM dbo.ACTIONS;
DELETE FROM dbo.PLANS;
DELETE FROM dbo.PARTIES;
DELETE FROM dbo.USERS;
DELETE FROM dbo.USERTYPE;
DELETE FROM dbo.CANTONS;
DELETE FROM dbo.PROVINCES;

DBCC CHECKIDENT ('dbo.CALIFICATIONS', RESEED, 0)
DBCC CHECKIDENT ('dbo.DELIVERABLES', RESEED, 0)
DBCC CHECKIDENT ('dbo.ACTIONS', RESEED, 0)
DBCC CHECKIDENT ('dbo.PLANS', RESEED, 0)
DBCC CHECKIDENT ('dbo.PARTIES', RESEED, 0)
DBCC CHECKIDENT ('dbo.USERS', RESEED, 0)
DBCC CHECKIDENT ('dbo.USERTYPE', RESEED, 0)
DBCC CHECKIDENT ('dbo.CANTONS', RESEED, 0)
DBCC CHECKIDENT ('dbo.PROVINCES', RESEED, 0)