USE [master]
GO
/****** Object:  Database [Aseni]    Script Date: 3/21/2022 5:55:01 PM ******/
CREATE DATABASE [Aseni]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Aseni', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Aseni.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Aseni_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Aseni_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Aseni] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Aseni].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Aseni] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Aseni] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Aseni] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Aseni] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Aseni] SET ARITHABORT OFF 
GO
ALTER DATABASE [Aseni] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Aseni] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Aseni] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Aseni] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Aseni] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Aseni] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Aseni] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Aseni] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Aseni] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Aseni] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Aseni] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Aseni] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Aseni] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Aseni] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Aseni] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Aseni] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Aseni] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Aseni] SET RECOVERY FULL 
GO
ALTER DATABASE [Aseni] SET  MULTI_USER 
GO
ALTER DATABASE [Aseni] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Aseni] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Aseni] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Aseni] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Aseni] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Aseni] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Aseni', N'ON'
GO
ALTER DATABASE [Aseni] SET QUERY_STORE = OFF
GO
USE [Aseni]
GO
/****** Object:  Table [dbo].[ACTIONS]    Script Date: 3/21/2022 5:55:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACTIONS](
	[IdAction] [int] IDENTITY(1,1) NOT NULL,
	[IdPlan] [int] NOT NULL,
	[Description] [varchar](120) NOT NULL,
 CONSTRAINT [PK_ACTIONS] PRIMARY KEY CLUSTERED 
(
	[IdAction] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Califications]    Script Date: 3/21/2022 5:55:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Califications](
	[IdCalification] [int] IDENTITY(1,1) NOT NULL,
	[IdUser] [int] NOT NULL,
	[IdDeriverable] [int] NOT NULL,
	[Value] [float] NOT NULL,
	[PostTime] [datetime] NOT NULL,
 CONSTRAINT [PK_Califications] PRIMARY KEY CLUSTERED 
(
	[IdCalification] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CANTONS]    Script Date: 3/21/2022 5:55:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CANTONS](
	[IdCanton] [int] IDENTITY(1,1) NOT NULL,
	[IdProvince] [int] NOT NULL,
	[Name] [varchar](32) NOT NULL,
 CONSTRAINT [PK_CANTONS] PRIMARY KEY CLUSTERED 
(
	[IdCanton] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DELIVERABLES]    Script Date: 3/21/2022 5:55:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DELIVERABLES](
	[IdDeriverable] [int] IDENTITY(1,1) NOT NULL,
	[IdAction] [int] NOT NULL,
	[IdPlan] [int] NOT NULL,
	[IdCanton] [int] NOT NULL,
	[KPIValue] [int] NOT NULL,
	[KPIType] [varchar](8) NOT NULL,
	[PostTime] [datetime] NOT NULL,
	[CheckSum] [varchar](64) NOT NULL,
 CONSTRAINT [PK_DELIVERABLES] PRIMARY KEY CLUSTERED 
(
	[IdDeriverable] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PARTIES]    Script Date: 3/21/2022 5:55:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PARTIES](
	[IdParty] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](32) NOT NULL,
	[Description] [varchar](max) NOT NULL,
	[UrlFlag] [varchar](32) NOT NULL,
	[CreationDate] [datetime] NOT NULL,
 CONSTRAINT [PK_PARTIES] PRIMARY KEY CLUSTERED 
(
	[IdParty] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PLANS]    Script Date: 3/21/2022 5:55:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PLANS](
	[IdPlan] [int] IDENTITY(1,1) NOT NULL,
	[IdParty] [int] NOT NULL,
	[Title] [varchar](64) NOT NULL,
	[Description] [varchar](max) NOT NULL,
 CONSTRAINT [PK_PLANS] PRIMARY KEY CLUSTERED 
(
	[IdPlan] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PROVINCES]    Script Date: 3/21/2022 5:55:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROVINCES](
	[IdProvince] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](32) NOT NULL,
 CONSTRAINT [PK_PROVINCES] PRIMARY KEY CLUSTERED 
(
	[IdProvince] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERS]    Script Date: 3/21/2022 5:55:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS](
	[IdUser] [int] IDENTITY(1,1) NOT NULL,
	[IdUserType] [int] NOT NULL,
	[IdCanton] [int] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[LastName] [varchar](50) NOT NULL,
	[Password] [varchar](50) NOT NULL,
	[UrlPicture] [varchar](50) NOT NULL,
	[CreationDate] [datetime] NOT NULL,
	[IdenNumber] [varchar](50) NOT NULL,
 CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
(
	[IdUser] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERTYPE]    Script Date: 3/21/2022 5:55:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERTYPE](
	[IdUserType] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](32) NOT NULL,
 CONSTRAINT [PK_USERTYPE] PRIMARY KEY CLUSTERED 
(
	[IdUserType] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACTIONS]  WITH CHECK ADD  CONSTRAINT [FK_ACTIONS_PLANS] FOREIGN KEY([IdPlan])
REFERENCES [dbo].[PLANS] ([IdPlan])
GO
ALTER TABLE [dbo].[ACTIONS] CHECK CONSTRAINT [FK_ACTIONS_PLANS]
GO
ALTER TABLE [dbo].[Califications]  WITH CHECK ADD  CONSTRAINT [FK_Califications_DELIVERABLES] FOREIGN KEY([IdDeriverable])
REFERENCES [dbo].[DELIVERABLES] ([IdDeriverable])
GO
ALTER TABLE [dbo].[Califications] CHECK CONSTRAINT [FK_Califications_DELIVERABLES]
GO
ALTER TABLE [dbo].[Califications]  WITH CHECK ADD  CONSTRAINT [FK_Califications_USERS] FOREIGN KEY([IdUser])
REFERENCES [dbo].[USERS] ([IdUser])
GO
ALTER TABLE [dbo].[Califications] CHECK CONSTRAINT [FK_Califications_USERS]
GO
ALTER TABLE [dbo].[CANTONS]  WITH CHECK ADD  CONSTRAINT [FK_CANTONS_PROVINCES] FOREIGN KEY([IdProvince])
REFERENCES [dbo].[PROVINCES] ([IdProvince])
GO
ALTER TABLE [dbo].[CANTONS] CHECK CONSTRAINT [FK_CANTONS_PROVINCES]
GO
ALTER TABLE [dbo].[DELIVERABLES]  WITH CHECK ADD  CONSTRAINT [FK_DELIVERABLES_ACTIONS] FOREIGN KEY([IdAction])
REFERENCES [dbo].[ACTIONS] ([IdAction])
GO
ALTER TABLE [dbo].[DELIVERABLES] CHECK CONSTRAINT [FK_DELIVERABLES_ACTIONS]
GO
ALTER TABLE [dbo].[DELIVERABLES]  WITH CHECK ADD  CONSTRAINT [FK_DELIVERABLES_CANTONS] FOREIGN KEY([IdCanton])
REFERENCES [dbo].[CANTONS] ([IdCanton])
GO
ALTER TABLE [dbo].[DELIVERABLES] CHECK CONSTRAINT [FK_DELIVERABLES_CANTONS]
GO
ALTER TABLE [dbo].[DELIVERABLES]  WITH CHECK ADD  CONSTRAINT [FK_DELIVERABLES_PLANS] FOREIGN KEY([IdPlan])
REFERENCES [dbo].[PLANS] ([IdPlan])
GO
ALTER TABLE [dbo].[DELIVERABLES] CHECK CONSTRAINT [FK_DELIVERABLES_PLANS]
GO
ALTER TABLE [dbo].[PLANS]  WITH CHECK ADD  CONSTRAINT [FK_PLANS_PARTIES] FOREIGN KEY([IdParty])
REFERENCES [dbo].[PARTIES] ([IdParty])
GO
ALTER TABLE [dbo].[PLANS] CHECK CONSTRAINT [FK_PLANS_PARTIES]
GO
ALTER TABLE [dbo].[USERS]  WITH CHECK ADD  CONSTRAINT [FK_USERS_CANTONS] FOREIGN KEY([IdCanton])
REFERENCES [dbo].[CANTONS] ([IdCanton])
GO
ALTER TABLE [dbo].[USERS] CHECK CONSTRAINT [FK_USERS_CANTONS]
GO
ALTER TABLE [dbo].[USERS]  WITH CHECK ADD  CONSTRAINT [FK_USERS_USERTYPE] FOREIGN KEY([IdUserType])
REFERENCES [dbo].[USERTYPE] ([IdUserType])
GO
ALTER TABLE [dbo].[USERS] CHECK CONSTRAINT [FK_USERS_USERTYPE]
GO
/****** Object:  StoredProcedure [dbo].[GetPlayer]    Script Date: 3/21/2022 5:55:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--------------------------------------------------------------------------
CREATE PROCEDURE [dbo].[GetPlayer]
--------------------------------------------------------------------------
-- GetPlayer
-- Gunther Karolyi
-- Bases II
-- Grupo 01
/*
 Returns players with the same password
*/
--------------------------------------------------------------------------

@Password varchar(32)

AS
	-- Get Time Zone Offset
	DECLARE @Offset int = DATEPART(tzoffset,SYSDATETIMEOFFSET())

	-- Return Players
	SELECT 
		Username,
		LastModification AS DateUTC,
		DATEADD(MINUTE, @Offset, LastModification) AS Localtime
	FROM dbo.PLAYERS
	WHERE [Password] = @Password
	ORDER BY Username;
	
	
GO
/****** Object:  StoredProcedure [dbo].[InsertPlayer]    Script Date: 3/21/2022 5:55:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--------------------------------------------------------------------------
CREATE PROCEDURE [dbo].[InsertPlayer]
--------------------------------------------------------------------------
-- InsertPlayer
-- Gunther Karolyi
-- Bases II
-- Grupo 01
/*
 Inserts a new register in the PLAYERS table
*/
--------------------------------------------------------------------------
@Username varchar(32),
@Password varchar(32),
@LastMod datetime

AS
	-- Get Time Zone Offset
	DECLARE @Offset int = DATEPART(tzoffset,SYSDATETIMEOFFSET())

	-- Insert New Player
	INSERT INTO [dbo].[PLAYERS]
           ([Username]
           ,[Password]
           ,[LastModification])
     VALUES
           (@Username
           ,@Password
           ,DATEADD(MINUTE, -@Offset, @LastMod))
	
GO
/****** Object:  StoredProcedure [dbo].[Query1]    Script Date: 3/21/2022 5:55:01 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--------------------------------------------------------------------------
CREATE PROCEDURE [dbo].[Query1]
--------------------------------------------------------------------------
-- Query1
/*
 Listar todos los entregables agrupados por partido para un cantón dado 
 por parámetro y cada hilo usa un cantón diferente.
*/
--------------------------------------------------------------------------
@IdCanton int
AS
	
	SELECT 
		ACTIONS.[Description] + CAST(DELIVERABLES.KPIValue AS varchar(16)) + DELIVERABLES.KPIType AS [Description],
		PARTIES.[Name] AS 'Party'
	FROM dbo.DELIVERABLES 
		JOIN dbo.PLANS  WITH(NOLOCK) ON (DELIVERABLES.IdPlan = PLANS.IdPlan)
		JOIN dbo.ACTIONS WITH (NOLOCK) ON (DELIVERABLES.IdAction = ACTIONS.IdAction)
		JOIN dbo.PARTIES WITH(NOLOCK) ON (PLANS.IdParty = PARTIES.IdParty)
	WHERE IdCanton = @IdCanton
	ORDER BY PLANS.IdParty;
GO
USE [master]
GO
ALTER DATABASE [Aseni] SET  READ_WRITE 
GO
